android.enableJetifier=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options="-Xmx4096M"
android.javaCompile.suppressSourceTargetDeprecationWarning=true
# Ensure Gradle uses JDK 17 which is compatible with AGP 8.x
# org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64
